language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=examples/basic_decode
install:
    - pip install -U platformio
    - platformio update
    - cd ~ && git clone https://github.com/bxparks/UnixHostDuino.git && cd -
script:
    - platformio ci --lib="." --board=ttgo-lora32-v1
    - cd examples/basic_decode && make clean && make && ls -al && cd -
