language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=examples/basic_decode
install:
    - pip install -U platformio
    - platformio update
script:
    - platformio ci --lib="." --board=ttgo-lora32-v1 --board=d1_mini
